# Schema for the configuration files of the Path module.

field.widget.settings.path:
  type: mapping
  label: 'Link format settings'
  mapping:
    orderable:
      type: boolean
      label: 'Orderable'
