<?php

/**
 * @file
 * Driver test module.
 */

// cspell:ignore databasemodule databasedriver

/**
 * Implements DATABASEMODULE_views_data_DATABASEDRIVER_alter().
 */
function driver_test_views_data_drivertestmysql_alter(&$data) {
  \Drupal::state()->set('driver_test_views_data_drivertest_alter', TRUE);
}

/**
 * Implements DATABASEMODULE_views_data_DATABASEDRIVER_alter().
 */
function driver_test_views_data_drivertestpgsql_alter(&$data) {
  \Drupal::state()->set('driver_test_views_data_drivertest_alter', TRUE);
}
